apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./edu/user
- ./edu/goods
images:
- name: hmschlng/edu-goods
  newTag: "202501221558"
- name: hmschlng/edu-user
  newTag: "202501221558"
