apiVersion: v1
kind: Service
metadata:
  name: edu-user-service
  namespace: edu-user
spec:
  selector:
    app: edu-user-prod
    version: blue  # 기본적으로 Blue 배포에 연결
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   

---
apiVersion: v1
kind: Service
metadata:
  name: edu-goods-service
  namespace: edu-goods
spec:
  selector:
    app: edu-goods-app
    version: blue  # 기본적으로 Blue 배포에 연결
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 