name: CI for edu-user

on:
  workflow_call:

env:
  REPO_ACCOUNT: hmschlng
  SERVICE_NAME: edu-goods
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: '1. Checkout Service Repository'
        uses: actions/checkout@v4
        with:
          repository: ${{env.REPO_ACCOUNT}}/${{env.SERVICE_NAME}}
          path: ${{env.SERVICE_NAME}}
          token: ${{secrets.REPO_TOKEN}}

      - name: '2. Set up JDK ${{env.JAVA_VERSION}}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'

      - name: '3. Build with Gradle Wrapper'
        context: ${{env.SERVICE_NAME}}
        run: |
          ls -al
          ./gradlew build

      - name: '4. Dockerhub login'
        uses: docker/login-action@v1
        with:
          login-server: ${{ secrets.DOCKERHUB_LOGIN_SERVER }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: '5. Gen Version'
        id: gen-version
        run: |
          export TZ=Asia/Seoul
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: '6. Build & Tag Image'
        run: |
          cd edu-user
          docker build -t ${{ secrets.DOCKERHUB_LOGIN_SERVER  }}/edu-user:${{ env.VERSION }} -f Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_LOGIN_SERVER  }}/edu-user:${{ env.VERSION }} ${{ env.REPO_ACCOUNT  }}/edu-user:${{ env.VERSION }}

      - name: '7. Push image'
        uses: docker/login-action@v1
        with:
          login-server: ${{ secrets.DOCKERHUB_LOGIN_SERVER  }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
